MODEL:
  BACKBONE:
    NAME: 'vgg16'
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    BOX_PREDICTOR: 'vgg16_predictor'
    POOL_TYPE: 'align'
DATASETS:
  TRAINS: ['kitti_train']
  TESTS: ['cityscapes_car_val']
INPUT:
  TRANSFORMS_TRAIN:
    - name: 'random_flip'
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [102.9801, 115.9465, 122.7717]
      std: [1, 1, 1]
      to_bgr: True
    - name: 'collect'
  TRANSFORMS_TEST:
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [102.9801, 115.9465, 122.7717]
      std: [1, 1, 1]
      to_bgr: True
    - name: 'collect'
SOLVER:
  EPOCHS: 20
  STEPS: (16, 18)
  LR: 0.001
  BATCH_SIZE: 1
TEST:
  EVAL_TYPES: ['voc']

WORK_DIR: './work_dir/baseline_kitti'