MODEL:
  BACKBONE:
    NAME: 'resnet101'
  RPN:
    POST_NMS_TOP_N_TEST: 300
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
    BATCH_SIZE_PER_IMAGE: 128
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
    BOX_PREDICTOR: 'resnet101_predictor'
DATASETS:
  TRAINS: ['voc_2007_trainval', 'voc_2012_trainval']
  TESTS: ['voc_clipart_traintest']
INPUT:
  TRANSFORMS_TRAIN:
    - name: 'random_flip'
    - name: 'resize'
      min_size: [600]
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
  TRANSFORMS_TEST:
    - name: 'resize'
      min_size: [600]
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
SOLVER:
  EPOCHS: 10
  STEPS: (8, 9)
  LR: 1e-5
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 1
TEST:
  EVAL_TYPES: ['voc']

WORK_DIR: './work_dir/clipart'